import pyautogui
import time
import subprocess


subprocess.Popen(['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'])


time.sleep(3)


pyautogui.write('https://ui.vision/demo/webtest/frames/')
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write("content1",interval=0.1)
pyautogui.sleep(2)                   
# pyautogui.sleep(

pyautogui.press('tab')
time.sleep(1)
pyautogui.write("content2",interval=0.1)
pyautogui.sleep(2)
pyautogui.press('tab')
pyautogui.write("content3",interval=0.1)
pyautogui.sleep(2)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('tab')
pyautogui.press('space')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('space')
time.sleep(3)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('space')
time.sleep(2)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.write("content23",interval=0.1)
time.sleep(3)
pyautogui.press('tab')
time.sleep(3)
pyautogui.write("content24",interval=0.1)
time.sleep(3)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('space')
time.sleep(3)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.write("content4",interval=0.1)
time.sleep(3)
pyautogui.press('tab')
time.sleep(3)
pyautogui.write("content5",interval=0.1)
time.sleep(3)
pyautogui.press('tab')
time.sleep(2)
pyautogui.press('enter')
